version: '3.8'

services:
  app:
    build:
      context: .
      args:
        MODEL_URL: ${MODEL_URL}
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MODEL_URL=${MODEL_URL}
      - PORT=${PORT}
