version: '3.8'

services:
  app:
    build:
      context: .
      args:
        MODEL_URL: ${MODEL_URL}
    ports:
      - "${PORT}:8000"
    environment:
      - MODEL_URL=${MODEL_URL}
      - PORT=${PORT}
